### PR TITLE
Fixing cast call in schema files #93

### PR DESCRIPTION
**Pull request by sashman**
Adding an import and wrapping fields in a list.

### CODE REVIEW

**Comment by jhartwell** [comment]
@sashman is this the only change that is needed to support ecto 3? it seems like there would need to be more changes than this

**Comment by sashman** [comment]
Not sure about that, the PR title should probably say "fix cast call" 🤔

**Comment by sashman** [comment]
@jhartwell I've changed the title of this PR, so it can focus on a specific issue if you know of any other ecto 3 related problems I'm happy to help out :)

**Comment by jhartwell** [comment]
@sashman this has been merged, thanks and sorry for the delay

**Comment by sashman** [comment]
Awesome thanks!

**Pull request merged**
